### ISSUE TITLE
Configuration is editable by the user

### ISSUE THREAD

**Issue by rissson** [ddorn/pyconfiglib#2]
Don't save it in an editable format

**Comment by rissson** [comment]
Even better: add option to save as editable or not format. Or even to choose between formats

**Comment by ddorn** [comment]
With #6, you can now set `__xor_key__` to a byte string to xor the configuration file and make it not editable easily by the user.

Furthermore, you can override `__crypt__` and `__decrypt__` to change the encryption method.
