### ISSUE TITLE
Add __str__ function

### ISSUE THREAD

**Issue by rissson** [ddorn/pyconfiglib#5]
`__str__` function should be added to allow the user of the library to retrieve the current configuration as a string.

**Comment by rissson** [comment]
Also, maybe add an option to get a nice and beautiful formatted JSON string, and one to get a oneliner

**Comment by ddorn** [comment]
With #6, you can now use the builtin`str` to get the configuration as a string, indented and not colored, and `repr` to get the same in one line.
